buildNumber: ${buildNumber}
buildTime: ${buildTime}
gitRevision: ${gitRevision}
gitBranch: ${gitBranch}

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/easydojo-template-mysql?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_bin&useServerPrepStmts=false&rewriteBatchedStatements=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root

easydojo:
  template:
    jwtSecret: whateversecret
    jwtExpireMinutes: 30