management.endpoints.web.exposure.include: "*"

spring:
  profiles:
    active: local
  flyway:
    enabled: true
    encoding: 'UTF-8'
    cleanDisabled: true
    outOfOrder: false
    validateOnMigrate: true
    cleanOnValidationError: false
    checkLocation: true
    baselineDescription: 'initMigrate'
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
    open-in-view: false

logging:
  pattern:
    console: "%date{yyyy-MM-dd HH:mm:ss.SSS,Asia/Shanghai} %X{requestId}-%X{userId} %highlight(%-5level) %logger{36} : %m%n%wEx"
    file: "%date{yyyy-MM-dd HH:mm:ss.SSS,Asia/Shanghai} %X{requestId}-%X{userId} %highlight(%-5level) %logger{36} : %m%n%wEx"


