CREATE TABLE PRODUCT
(
    ID           VARCHAR(32) NOT NULL,
    NAME         VARCHAR(50)  NOT NULL,
    PRICE        DECIMAL NOT NULL,
    DESCRIPTION  VARCHAR(100) DEFAULT NULL,
    CREATED_AT   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_AT    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
